#!/bin/sh

set -e

cd ..
rm -f *_*.tar.gz
R CMD build code &> /dev/null
[ ! -d ~/xran ] && mkdir ~/xran && git clone git@github.com:yihui/xran.git ~/xran
cp *_*.tar.gz ~/xran/src/contrib/
R_PKG=$(echo *_*.tar.gz | cut -d_ -f1)
Rscript -e "setwd('~/xran/src/contrib'); unlink(paste0('$R_PKG', '_*')"
        -e "tools::write_PACKAGES('.', 'source')"
cd ~/xran/
git add * && git commit --amend -m"add new packages" && git push -f origin gh-pages
