#!/bin/sh

set -e

cd ..
rm -f *_*.tar.gz
R CMD build $R_PKG &> /dev/null
[ ! -d ~/xran ] && mkdir ~/xran && git clone git@github.com:yihui/xran.git ~/xran
rm -f ~/xran/src/contrib/$R_PKG_*.tar.gz
cp *_*.tar.gz ~/xran/src/contrib/
Rscript -e "tools::write_PACKAGES('~/xran/src/contrib', 'source')"
cd ~/xran/
git add * && git commit --amend -m"add new packages" && git push -f origin gh-pages
